Выполнено ДЗ №3
Smirnoffspb78/lessons pull request #1
Opened 2024-02-10 09:13 UTC by Smirnoffspb78

Выполнено ДЗ №3

2024-02-10 11:19 UTC, daniiladamov requested changes

2024-02-10 11:19 UTC, daniiladamov commented on src/lessonthree/Lesson03HomeWork.java
> +package lessonthree;
почему названия пакетов пляшут в проекте?

2024-02-10 11:19 UTC, daniiladamov commented on src/lessonthree/Lesson03HomeWork.java
> +        var random = Math.random() * 491 + 10;
нуууу, тут отрезок формирования от [10, 501]. Зайди в метод random(), там написано как формировать число в определенном отрезке

2024-02-10 11:19 UTC, daniiladamov commented on src/lessonthree/Lesson03HomeWork.java
> +        random = random > 500 ? 500 : random;
эту проверку можно убрать правильным формированием числа в заданных границах.
Вообще, для генерации псевдослучайных лучше использовать класс ThreadLocalRandom, его интерфейс почти такой же, но формировать значения в диапазоне проще

2024-02-10 11:19 UTC, daniiladamov commented on src/lessonthree/Lesson03HomeWork.java
> +        if (random > 25 && random < 200) System.out.println(" попало в интервал (25; 200)");
в целом, я бы ещё предложил, каждую задачу выносить в отдельный метод, а не писать все в в методе main. Из main лучше просто дергать эти методы (тогда все описание можно в javadoc написать), да и в целом, лучше смотреться будет (если от вас, конечно, не требуют именно так писать)

2024-02-10 11:19 UTC, daniiladamov commented on src/lessonthree/Lesson03HomeWork.java
> +      /*  Задача #2 на if else
прям напрашивается отдельным методом, который принимает две координаты в качестве аргументов

2024-02-10 11:19 UTC, daniiladamov commented on src/lessonthree/Lesson03HomeWork.java
> +        Дана переменная monthNumber, которая хранит порядковый номера месяца. И переменная isLeap, которая хранит информацию о том, является ли год високосным.
прям напрашивается отдельным методом, который принимает номер месяца и количество дней в году (хотя я бы тебе тут предложил передавать год и по его значению высчитывать, високосный он или нет)

2024-02-10 11:19 UTC, daniiladamov commented on src/lessonthree/Lesson03HomeWork.java
> +        Даны переменные couponNumber - номер купона и resultSum - сумма покупки.
тоже методом напрашивается с аргументами: номер купона и сумма (возвращает скидку, допустим, или сумму с учетом скидки)

2024-02-10 11:19 UTC, daniiladamov commented on src/lessonthree/Lesson03HomeWork.java
> +        resultSum = switch (couponNumber) {
пересчитывать входной параметр - такая себе затея, лучше всегда возвращать новое значение

2024-02-11 12:31 UTC, Smirnoffspb78 commented on src/lessonthree/Lesson03HomeWork.java
> +package lessonthree;
учтено

2024-02-11 13:58 UTC, Smirnoffspb78 commented on src/lessonthree/Lesson03HomeWork.java
> +        Дана переменная monthNumber, которая хранит порядковый номера месяца. И переменная isLeap, которая хранит информацию о том, является ли год високосным.
Учтено вычисление високосного года. Переменная numberOfDayInYear инициализируется через тернарный опрератор

2024-02-11 13:59 UTC, Smirnoffspb78 commented on src/lessonthree/Lesson03HomeWork.java
> +      /*  Задача #2 на if else
Решение задач отдельными методами будет учтено в следующих ДЗ

2024-02-11 14:02 UTC, Smirnoffspb78 commented on src/lessonthree/Lesson03HomeWork.java
> +        if (random > 25 && random < 200) System.out.println(" попало в интервал (25; 200)");
Написание методов будет учтено в следующих ДЗ

2024-02-11 14:16 UTC, Smirnoffspb78 commented on src/lessonthree/Lesson03HomeWork.java
> +        resultSum = switch (couponNumber) {
Учтено.  Введена переменная resultSumWithoutDiscount. resultSumWithoutDiscount остается неизменным, а resultSum инициализируется с помощью блока switch.

2024-02-11 14:16 UTC, Smirnoffspb78 commented on src/lessonthree/Lesson03HomeWork.java
> +        Даны переменные couponNumber - номер купона и resultSum - сумма покупки.
Решение задач отдельными методами будет учтено в следующих ДЗ

2024-02-11 14:37 UTC, Smirnoffspb78 commented on src/lessonthree/Lesson03HomeWork.java
> +        random = random > 500 ? 500 : random;
Учтено. Костыль удален, все переменные теперь целочисленные

2024-02-11 15:08 UTC, daniiladamov approved these changes

2024-02-11 15:28 UTC, merged