Home work14
Smirnoffspb78/lessons pull request #10
Opened 2024-03-14 21:39 UTC by Smirnoffspb78

2024-03-15 08:41 UTC, daniiladamov requested changes
Не надо ответвляться от несмерженных веток, тут это не нужно вообще (посмотри на количество файлов и коммиты в в этом ПР), вот ты его раньше всех сольешь и все твои изменения для прошлых ДЗ попадёт в main. Потом внесешь правки в других ПР и получишь конфликты

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/vehicle/Task14.java
> +        K[] arr = {};
таким образом массив обобщенный вообще не заполнить, так как массивы ковариантны и  плохо совместимы с типами. Гипотетически в массив типа K, можно было бы запихать только объект second, но создать или скастить нормально, и потом его получить ты не сможешь, так как не знаешь тип K в рантайме и не сможешь создать массив этого типа, будешь ошибки ловить только.
Поковыряйся и попробуй что-нибудь добавить туда и получить массив типа K после вызова метода

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/vehicle/Task14.java
> +        // экземпляры каких классов передать?
а на это вопрос какие ответы?

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +public class ReturnPairContainer<T extends Number> {
1. Зачем вообще этот класс?
2. Зачем он параметризован?
3. Зачем нужен объект этого класса?

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +    public PairContainer<T> returnPairContainer(T[] arr) {
этот метод явно напоминает фабричный метод для получения объекта PairContainer. Поэтому, этому методу место в PairContainer и быть ему статическим

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/Main.java
> +        BigDecimal[] bigDecimals={BigDecimal.valueOf(1),BigDecimal.valueOf(1),BigDecimal.valueOf(2),BigDecimal.valueOf(3)};
че он тут без дела валяется?

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/Main.java
> +        System.out.println(ret.returnPairContainer(doubles));
это все очень хорошо, но попробуй получить нужный тип значения из PairContainer
Тут и ниже

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +        Number temp;
temp всегда имеет тип Double

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +            temp = t.doubleValue() % 2;
автоупаковка

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +        Number sumOfEvenNumbers = 0;
эти переменные сначала хранят Integer (при инициализации), а потом всегда Double

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +            sumOfEvenNumbers = temp.equals(0.0) ? t.doubleValue() + sumOfEvenNumbers.doubleValue() : sumOfEvenNumbers;
1.Автораспаковка тут: temp.equals(0.0)
2. Автоупаковка при присвоении (складываются примитивы, кладутся в объект типа Double)
3. Лучше сравнивать примитивы, возможность у тебя есть, используй Double.compare()

2024-03-15 08:41 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +        return (PairContainer<T>) new PairContainer<>(sumOfEvenNumbers, sumOfOddNumbers);
ну, тип ты приведешь, а вот объекты sumOfEvenNumbers и sumOfOddNumbers всегда будут Double, при извлечении говна можно поесть
Тут смысла в параметризованном PairContainer как бы и нет, получается (так как всегда double будет)

2024-03-16 07:11 UTC, Smirnoffspb78 commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +public class ReturnPairContainer<T extends Number> {
1,2) Класс удален

2024-03-16 07:12 UTC, Smirnoffspb78 commented on src/com/smirnov/project/lesson14/homework14/task2/ReturnPairContainer.java
> +    public PairContainer<T> returnPairContainer(T[] arr) {
Конструктор сделан приватны, объекты создаются внутри статического метода, расположенного внутри класс

2024-03-16 12:20 UTC, daniiladamov approved these changes

2024-03-16 12:20 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/PairContainer.java
> +public final class PairContainer<T extends Number> {
можно было record написать, он сюда с виду хорошо подходит

2024-03-16 12:20 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/PairContainer.java
> +        double sumOfEvenNumbers = 0.0;
можно вместо 0.0 писать 0d, это так, для общего развития (мне так больше наравиться, так как такой варик норм читается совместно с var)

2024-03-16 12:20 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/PairContainer.java
> +            if (t == null) throw new NullPointerException("arr[i]=null");
как вариант, можно null-значения просто пропускать

2024-03-16 12:20 UTC, daniiladamov commented on src/com/smirnov/project/lesson14/homework14/task2/PairContainer.java
> +        if (arr[0] instanceof Byte) {
так, мне тут много что не нравится, но раз надо прям тип сохранить, окэээээээээээй
1. Принимает метод всех наследников Number, а вот обработает только часть (т.е. нормально вернёт значения из контейнера - из-за строки 60)
2. Весь это блок просто смотрится не оч, у тебя в java 21 есть pattern matching по классам, лучше используй его для таких выражений, он прям очень сюда просится
3.  Тут есть прикол, что сумма может выйти за допустимый край(при обрезании double, да и просто при сложении сам double может не вывести), это ладно, но ты помни об этом

2024-03-17 14:50 UTC, merged