Homework15
Smirnoffspb78/lessons pull request #11
Opened 2024-03-16 18:12 UTC by Smirnoffspb78

2024-03-16 21:19 UTC, daniiladamov requested changes

2024-03-16 21:19 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitToStorageInfo.java
> +        if (type == null) throw new NullPointerException("type=null");
Objects.requireNonNull(),

2024-03-16 21:19 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +        ArrayList<FruitToStorageInfo> fruitsByTypeAndPrice = new ArrayList<>();
тип переменной

2024-03-16 21:19 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +                fruitsByTypeAndPrice.add(fruit.clone());
если рассматривать это хранилище, как некоторую коллекцию, то смысла отдавать клонов нет

2024-03-16 21:19 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +            fruitToStorageInfo.setCount(numberOfEmptySlots);
лучше входящий объект не менять, а просто выбросить исключение, что он уже не влезает

2024-03-17 07:50 UTC, Smirnoffspb78 commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +        double minPrice = Double.POSITIVE_INFINITY;
Не, мы здесь не создаем новые фрукты. 

Эта штука была сделана только для проверки наличия типа. Если тип есть, то первая же проверка это значение поменяет, а если нет типа фрукта, то возвращается ноль. Т.е. если бы мы были уверены в наличии всех фруктов, можно было бы начально значение взять у индекса "0". 

Для того, чтобы ничего не возвращать, можно бросить исключение о том, что тип в списке отсутствует, но в одной из домашек мы обсуждали, что это выглядит странно, что есть константы, которые доступны при использовании, при этом клиент их как-бы не может использовать (это решение было в конструкторе). Здесь ситуация аналогичная, что константы то есть, но их в конкретном списке просто может не оказаться.

2024-03-17 08:00 UTC, Smirnoffspb78 commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +    public HashSet<FruitToStorageInfo> getFruits() {
Хранящиеся фрукты на складе - является свойством объекта (его характеристикой). В моем представлении к ним должен быть доступ. Как должен быть доступ к цвету автомобиля или имени человека.

2024-03-17 08:07 UTC, Smirnoffspb78 commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +            fruitToStorageInfo.setCount(numberOfEmptySlots);
Можно просто наверно тогда false возвращать. Это лучше, чем исключение

2024-03-17 08:16 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +            fruitToStorageInfo.setCount(numberOfEmptySlots);
Почему и чем? Вы же проходили проверяемые исключения, вот тут теперь и можешь применить свои знания, сюда это очень хорошо подойдет

2024-03-17 08:16 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +    public HashSet<FruitToStorageInfo> getFruits() {
да не факт вообще, если у тебя есть апи для взаимодействия с объектом (та же коллекция), ты не имеешь доступ к исходной структуре этой коллекции (попробуй вот массив получить исходный из ArrayList). 
Все поля не надо отдавать, тем более при применении композиции - это один из способов расширения функциональности класса без наследования, и сам этот объект не факт что есть смысл отдавать, тем более если это не требуется

2024-03-18 07:36 UTC, daniiladamov approved these changes

2024-03-18 07:36 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +    public boolean addToStorage(FruitToStorageInfo toStorageInfo) throws MaxCountExceededException {
теперь у тебя всегда true, а если не добавилось - исключения, смысла в возвращаемом значении нет

2024-03-18 07:36 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +            fruit.setPrice(fruit.getPrice() * (1 + (double) value / 100));
можно упростить без приведений
(double) value / 100 => value / 100d

2024-03-18 07:36 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/FruitStorage.java
> +        Objects.requireNonNull(fruitType, "fruitType=null.");
можно не проверять, так как условие if не будет истинным fruit.getType() == null - всегда false и вернётся пустой List, либо сразу возвращать пустой лист при таком варианте

2024-03-18 07:36 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/MaxCountExceededException.java
> +    public MaxCountExceededException(String message, int numberOfEmptySlots) {
можно проще: просто передавать int, создать шаблон сообщения внутри класса и сгенерированное сообщение передавать в родительский конструктор, тогда не будет переопределять getMessage, и там будет лежать просто строка без доп. операций на конкотенацию
А такой конструктор можно уже добавлять по нужде использования исключения

2024-03-19 18:05 UTC, daniiladamov approved these changes

2024-03-19 18:05 UTC, daniiladamov commented on src/com/smirnov/project/lesson15/homework15/ComparatorsFruits.java
> +                return -Double.compare(fruit1.getPrice(), fruit2.getPrice());
зачем ты так, можно ж просто аргументы местами поменять

2024-03-21 19:09 UTC, merged