Выполнена основная часть курсовой работы №2
Smirnoffspb78/lessons pull request #21
Opened 2024-04-07 12:41 UTC by Smirnoffspb78

2024-04-10 07:23 UTC, daniiladamov reviewed
из оставшегося глобального
1. Все команды ссылаются на методы Game, поэтому Quest в командах не нужон, достаточно ссылки на Game
2. Класс Game занимается всеми командами, и записывать в Quest ничего не надо. Класс Qusest ассоциирован с Game и можеn через публичное Api запросить у объекта Game всю необходимую инфу, поэтому передавать Quest в методы Game тоже не надо

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        requireNonNull(pathSaveAndDownload);
см. выше про requireNonNull()

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    public void startGameProcess(Quest quest) {
про Quest см. выше

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        int id = 0;
а вот тут цикл forEach можно и нужно заменить на обычный for

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        Scanner scannerGame = new Scanner(in);
try with resources

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +                throw new IllegalArgumentException("Введенное число должно совпадать с номером одного из пунктов меню.");
а че так жестко то? Ты же позволяешь в меню херню ввести, тут то тоже можно ошибиться, кто из нас не ошибался в жизни, а?)

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +                startGameProcess(quest);
у тебя создается куча сканеров при каждом выборе варианта и не закрываются
лучше в цикл тоже переделай, который считывает до момента "Вернуться в меню")

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +                quest.setTempName(continueName);
вот и примеры плохо использования ООП:
У тебя Quest содержит Game, но Game в своих методах начинает менять состояние класса верхнего уровня.

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    public void continueGame(Quest quest) {
три метода ниже переделать по замечаниям выше

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +            quest.setContinueName(Files.readString(get(pathSaveAndDownload)));
readString() тоже можешь статически импортировать, как сделал с writeString() ниже

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    public boolean downloadGame(Quest quest) {
тут возвращаемое значение в коде использоваться не будет

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    public boolean saveGame(Quest quest) {
возвращаемое значение не используется

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +                    StandardOpenOption.CREATE //Создать, если нет файла //Проверить доступ к директории и доступ к файлу как-то тоже нужно
комменты удали

2024-04-10 07:23 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        Objects.requireNonNull(pathSaveAndDownload);
requireNonNull - статическим импорт + возвращаемое значение

2024-04-10 07:24 UTC, daniiladamov requested changes

2024-04-10 07:24 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    private String pathSaveAndDownload;
final?

2024-04-10 19:21 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    private String pathSaveAndDownload;
Вообще я делал сеттер для него, т.к. наверное путь может иногда меняться? Поэтому final тут нет. А может ли путь меняться вообще? Ну умозрительно буд-то бы да. Сегодня туда, завтра сюда записали. Но это не точно

2024-04-10 19:24 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        Objects.requireNonNull(pathSaveAndDownload);
Так, возвращаемое значение у меня используется (См. команду DownloadGame) Если игра загрузилась, то только тогда идет обращение к методу start

2024-04-10 19:25 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        Objects.requireNonNull(pathSaveAndDownload);
Гипотетически можно создать локальную переменную и переложить вызов метода start в Download в условный блок

2024-04-10 19:33 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        int id = 0;
А зачем, если мы все равно все данные из нашей структуры читаем?

2024-04-10 20:09 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Quest.java
> +            continueName = answersAndQuestions.keySet().stream()
Но мы так делать не должны. По заданию "Начать игру (игровой процесс запускается в первого параграфа)", а не оттуда, откуда захотел клиент

2024-04-10 20:29 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        Objects.requireNonNull(pathSaveAndDownload);
Сейчас так и переделал

2024-04-11 08:48 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Quest.java
> +            continueName = answersAndQuestions.keySet().stream()
Такая структура данных нужна для обеспечения итерации между парами "ключ-значение",  а ты используешь LinkedHashMap, только для получения первого элемента очень уродским способом , а потом чисто как HashMap - такое себе использование LinkeHashMap. Не текущий класс собирает эту мапу, это делает клиент, и твой вариант можно развернуть, что первым элементом положат не "Начать игру" - и как с этим будешь тогда быть?)
если был бы граф, то да, ты бы передал просто вершину (или массив состояний) - и тут вопросов бы не было

2024-04-11 08:53 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        int id = 0;
да тут на поверхности - видимость переменной id, которая дб быть только внутри цикла

2024-04-11 08:58 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    private String pathSaveAndDownload;
у тебя в проге это сеттер не используется, значит считаем, что нет такого функционала - для каждого объекта игрового процесса будет свой путь (или фолдер с сохранениями), и нормуль (можешь указать папку, а генерировать имя файла уже уникальное для каждого объекта, как вариант)

2024-04-12 18:51 UTC, daniiladamov approved these changes

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/command/Command.java
> +    Game game;
protected final

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/command/Command.java
> +    Command(String nameCommand, Game game) {
protected

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/command/StartGameCommand.java
> +        game.startGameProcess(game.getFirstQuest());
лучше перегрузи метод startGameProcess() или новый создай, типа startNewGame() в Game
с телом 
startGameProcess(firtstQuest)

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    Scanner scannerGame = new Scanner(in);
1. Я вообще против сканера в поле, нижу распишу
2. И почему он как поле без модификатора private и final тогда?

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        addAnswersAndQuestions(firstQuest, firstQuestionsParagraph, text);
не лучший вариант вызова (вспомни, как я тебе показывал пример с вызовом сеттера из конструктора)

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        this.firstQuest = firstQuest;
this.firstQuest = requireNonNull(firstQuest) ?

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        Objects.requireNonNull(continueName);
статический импорт потерялся тут

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        requireNonNull(answersAndQuestions);
answersAndQuestions и textsMap у тебя проинициализированы в полях, в этих проверках смысла нет тогда

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        for (int i = 0; i < answersAndQuestions.get(continueName).size(); i++) {
вынеси на строчку выше answersAndQuestions.get(continueName) в переменную - этот вызов несколько раз дальше дергается

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        if (answersAndQuestions.get(continueName).size() != 1) {
Я бы тут все завернул в try-with-resourrces
1. У тебя scanner тут нигде не закрывается
2. При выбросе исключения в блоке он освободит ресурсы автоматически
3. Рекурсивные вызовы тут отлично можно заменить циклом do-while (или while) внутри tryr-with-resources. Надо просто перезаписывать переменную continueName

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +            int userInput = scannerGame.nextInt();
у тебя пользователь может написать что-то типа "0123" или "ыпфапвла" или "1. Убить лисёнка", а не только число

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        }
мь тут какое-то сообщение тогда вывести, как ты ниже делаешь

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    public Map<String, String> getTextsMap() {
не используется

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    public Map<String, List<String>> getAnswersAndQuestions() {
зачем эту мапу наружу отдавать?

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Game.java
> +    public String getFirstQuest() {
см. коммент в StartGameCommand

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Main.java
> +        String quest1Text = "Каждое утро Лисёнок просыпался, завтракал и шёл увидеться с Бельчонком. Это утро не было исключением. Лисёнок пришёл на\n" +
ляяя, пришло время показать тебе магию
используй текстовые блоки, надо всего 6 кавычек написать
""" Пиши тут с переносами как хочешь
и сколько хочешь
""""

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Main.java
> +        System.out.println(game.getAnswersAndQuestions());
?

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +    public void execute(String name) {
private

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +        Optional.ofNullable(name)
после проверки name на nonNull, смысла его заворачивать в ofNullable нет, он точно не null уже
Может вызов menu.get(name) обернуть, в этом смысл будет

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +        Scanner scannerMenu = new Scanner(in);
что ж ты не хочешь никак использовать try-with-resources?
он закроет автоматически сканер (даже с исключением, в твоём варианте исключение если и возникнет, то явно до вызова scannerMenu.close())

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +            menuMap.entrySet().stream()
entrySet() -> values()

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/command/Command.java
> +    private final String nameCommand;
commandName

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +                    .map(Map.Entry::getKey)
Map.Entry::getKey => Command::getName

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +                    .filter(entry -> !((entry.getValue() instanceof SaveGameCommand || entry.getValue() instanceof ContinueGameCommand) && game.getTempName() == null
аааааааааааааа
мои глазааааааааааааа
мне больно

тут явно можно элегантно решить
вот тебе декларативный стиль фильтра, который я хочу тут видеть:
filter(Command::isDisplayed)
(подсказка: все команды содержат ссылку на Game)

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +    public Map<String, Command> getMenuMap() {
И почему он все ещё тут?)

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Quest.java
> +    void startMenu() {
public

2024-04-12 18:51 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Quest.java
> +    public Game getGame() {
удоли

2024-04-12 19:48 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Game.java
> +        this.firstQuest = firstQuest;
Не нужен, т.к. перед присвоением он передается в метод add. Там уже прошла проверка

2024-04-12 19:54 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Main.java
> +        System.out.println(game.getAnswersAndQuestions());
Я просто смотрел, все ли хорошо у моей мапы)

2024-04-12 20:12 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +        Optional.ofNullable(name)
После того, как сделали приват, есть ли смысл в проерке? в вообще теперь только через консоль что-то передаем

2024-04-13 08:20 UTC, daniiladamov commented on src/com/smirnov/project/courseproject2var2/Menu.java
> +        Optional.ofNullable(name)
Ну да, в таком слуаче не нужна, сканер вроде null никак не вернет, скорее упадет сам
А в Optional.ofNullable(map.get(..)) - смысл есть, так как ключа переданного может же не быть в твоей мапе

2024-04-14 18:00 UTC, merged