Выполнено ДЗ №6
Smirnoffspb78/lessons pull request #3
Opened 2024-02-17 07:48 UTC by Smirnoffspb78

2024-02-17 10:48 UTC, daniiladamov requested changes

2024-02-17 10:48 UTC, daniiladamov commented on src/lesson06/HomeWork06.java
> +        System.out.println("Остортированный массив пузырьковым методом" + Arrays.toString(BubbleMethod.bubbleMethod(arrayForBubbleMethod)));
тут и в 15 строчке.
Давай красиво делать, вызовы утильных классов через статический импорт, так нам Джошуа Блох заповедовал.

2024-02-17 10:48 UTC, daniiladamov commented on src/lesson06/BubbleMethod.java
> +    public static int[] bubbleMethod(int[] arr) {
погнали
Раз вы массивы прошли, значит знаешь, что это объект, а объект может быть null. Нам нужно бороться с NPE

2024-02-17 10:48 UTC, daniiladamov commented on src/lesson06/BubbleMethod.java
> +            if (check) {
смотри, это не лучшая практика (выходить из цикла через break, в современных языках от этого отходят). Если есть такая проверка, значит цикл можно заменить на while или do-while. Попробуй, так сделать, это уберет нужду в двух циклах for  и избавит от этой проверки, а ещё решение будет лаконичнее и короче смотреться

2024-02-17 10:48 UTC, daniiladamov commented on src/lesson06/BubbleMethod.java
> +        return arr;
Этот метод изменят исходный массив (попробуй вывести исходный теперь). Хорошая практика -  возвращать новый(ую) коллекцию/массив при вызове модернизирующих методов (и обязательно в функциональном программировании)

2024-02-17 10:48 UTC, daniiladamov commented on src/lesson06/SlidingWindow.java
> +        var number = 4;
по хорошему, это число должно быть константой, либо передавать его как метод аргумента, чтобы метод был гибким при управлении извне

2024-02-17 10:48 UTC, daniiladamov commented on src/lesson06/SlidingWindow.java
> +    public static int slidingWindow(int[] arr) {
здесь массив может быть null, а ещё и его длина может не соответствовать длине для расчета. Надо предусмотреть

2024-02-17 10:48 UTC, daniiladamov commented on src/lesson06/SlidingWindow.java
> +        for (int i = 0; i < number; i++) {
смотри, ты тут запускаешь два цикла (которые проходят весь массив от 0 до nubmer и от number до arr.length), это разбиение режет глаз немного, можно же всё это слить в один цикл

2024-02-17 14:54 UTC, Smirnoffspb78 commented on src/lesson06/SlidingWindow.java
> +        var number = 4;
Сделано константой

2024-02-19 06:06 UTC, daniiladamov approved these changes

2024-02-19 06:06 UTC, daniiladamov commented on src/lesson06/SlidingWindow.java
> +        final var number = 4;
константу надо было на уровне класса сделать, чтобы поведение метода зависело от константы

2024-02-19 06:06 UTC, daniiladamov commented on src/lesson06/SlidingWindow.java
> +        return maxSumma;}
скобкаааааааааа

2024-02-19 06:06 UTC, daniiladamov commented on src/lesson06/HomeWork06.java
> +            System.out.println("В метод sortedArray передан null");
давай в следующих занятиях будем отходить от использования SOUT (чтобы не привыкать), давай вместо этого логировать действия - см. класс Logger

2024-02-19 06:06 UTC, daniiladamov commented on src/lesson06/HomeWork06.java
> +        if (arrayForBubbleMethod == null) {
так-с
ты тут перенес проверки в клиента, но тут нет никаких входных данных для формирования массива, это не особо смысл имеет
Прошлый вариант был норм, клиент просто создал какой-то массив и вызвал метод - а все эти проверки лучше бы были в утильном классе

2024-02-19 06:06 UTC, daniiladamov commented on src/lesson06/HomeWork06.java
> +            sortedArray = new int[arrayForBubbleMethod.length];
я что-то прикола не понял)
тут клиент сам создаёт копию массива, а потом работает с копией, зачем?
Можно вернуть новый массив из утильного класса и работать с возвращаемым значением метода

2024-02-19 06:06 UTC, daniiladamov commented on src/lesson06/HomeWork06.java
> +        if (task02 == null) {
см. выше про проверки на клиенте

2024-02-19 06:06 UTC, daniiladamov commented on src/lesson06/SlidingWindow.java
> +        else {
можно и без этого else, а можно и с ним - ничего не изменится )

2024-02-20 05:30 UTC, daniiladamov commented on src/lesson06/BubbleMethod.java
> +            LOGGER.info(message);
переменную отдельную создавать тут не обязательно, если ты нигде эту строку, кроме как в логгере не используешь, можно прям внутри метода и писать 
Глянь потом на будущее шаблонизацию строк в логгере с использованием фигурных скобок (вместо конкотенации)

2024-02-20 05:31 UTC, daniiladamov commented on src/lesson06/SlidingWindow.java
> +        } else if (arr.length < 4) {
четверку тут и в 22 строке можно было бы завязать на константу

2024-02-20 05:31 UTC, daniiladamov approved these changes

2024-02-20 17:09 UTC, merged