Выполнено ДЗ №8
Smirnoffspb78/lessons pull request #5
Opened 2024-02-25 11:14 UTC by Smirnoffspb78

2024-02-25 14:03 UTC, daniiladamov requested changes

2024-02-25 14:03 UTC, daniiladamov commented on src/com/smirnov/project/lesson08/homework8/task2/MyAllowedProduct.java
> +            characterProduct = 0;
ага, смотри, а вот тут уже можно было бы и с бесконечностью поиграть (в отличие от продуктов), а то получается, что у нас может быть только жесткое ограничение по белкам, жирам и.т.д, либо сразу ноль, а вот продукт может содержать бесконечное число белков, жиров и.т.д. Такая себе абстракция
Типа можно было бы записать бесконечность, которая бы символизировала, что ограничения на этот элемент нет ( проверка бы всегда возвращала true по этому элементу для любого продукта), а вот если элемент меньше нуля, тут либо ноль писать тогда, либо исключение (я больше к исключению склоняюсь, конечно)

2024-02-27 06:03 UTC, daniiladamov requested changes

2024-02-27 06:03 UTC, daniiladamov commented on src/com/smirnov/project/lesson08/homework8/task1/GroupOfClimber.java
> +    private Climber[] climbersCopy;
а зачем её держать в качестве поля объекта?

2024-02-28 07:57 UTC, daniiladamov requested changes

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Vehicle.java
> +    private int number;
кмк, это должна быть строка)
И по логике это поле может быть финализированным

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Vehicle.java
> +            throw new IllegalArgumentException("Уровень износа не может быть отрицательным или быть больше 100");
если есть желание и время, давай все-таки выдадим комплексную информацию за раз после валидации всех полей

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Vehicle.java
> +     * Метод изменяет уровень износа транспортного средства.
По факту это восстановление транспортного средства (или ремонт)

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Train.java
> +    private boolean climateControl;
ориентируйся на нейминг булевых переменных с префиксами:
это (is)
содержит (has/contain)
может (can)
должен (shoud)
возможность (able)

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Train.java
> +            wearLevel--;
а если уровень износа меньше или равен нулю?
Можно, кстати, вызывать логику родителя таким образом super.repair() (в ней у тебя проверки уже есть)

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Train.java
> +            if (wearLevel < 0) {
можно все упростить типа 
wearLevel = Math.max(wearLevel - 2, 0)

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Bicycle.java
> +    private String type = "Городской";
не разноси переменные состояния и статические константы, пусть будет сгруппировано всё

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Bicycle.java
> +            throw new IllegalArgumentException("Количество колес должно быть от%dдо%d".formatted(MIN_WHEEL, MAX_WHEEL));
в конце строки пробелов бы навалить

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Vehicle.java
> +        if (wearLevel > 0)
а что тело if не в блоке?

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Bicycle.java
> +        if (numberWheel < MIN_WHEEL || numberWheel > MAX_WHEEL)
у тебя где-то тело if в блоке, а где-то нет, реши, на чьей ты стороне)
тут и в 53 строке

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Scooter.java
> +public class Scooter extends Bicycle {
в задании же самокат - транспортное средство с доп. свойствами, почему от велика наследуешь?
При таком наследовании ты можешь ещё один конструктор сделать и создать самокат с 4мя колёсами

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Scooter.java
> +    private boolean electrical;
нейминг

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Scooter.java
> +        if (wearLevel < 0) {
от этого блока можно избиваться с использованием Math.max()

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +    private Vehicle[] copyVehicles;
зачем здесь это поле?
оно лишнее и просто место занимает

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +        if (lengthWorkshop < 1) throw new IllegalArgumentException("Длина массива Vehicle не может быть отрицательной");
тело блока if

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +     * @throws IllegalArgumentException - если дина Vehicle не положительная
"не положительная" - либо слитно напиши, либо уж "отрицательная")
и тут не про длину машины (почему на английском написал?), а про размер мастерской тогда уж

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +            counter++;
инкремент можно в 48 строку перенести

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +        int checkRepair = 0;
очень странно метод реализован
по факту надо было:
1. Бежать по всему массиву 
2. У каждого ТС вызвать метод repair
3. Заннулить ссылку
4. В конце counter присвоить 0

Зачем вообще переменная checkRepair? Зачем перестановки в массиве? Это всё от лукавого
Проверь вообще состояние объекта WorkShop после вызова repairAll()

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +    public void repairAllFull() {
этого метода в задании не было

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +        return copyVehicles;
можно же просто вернуть vehicles.clone(), или подмассив до counter
хранение данных в переменной copyVehicles - излишне

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +    public int getCounter() {
это внутренняя переменная, которая юзается только внутри методов, она наружу не нужна

2024-02-28 07:57 UTC, daniiladamov commented on src/com/smirnov/project/lesson09/homework09/Main.java
> +        System.out.println(Arrays.toString(workshop.getVehicles()));
этот вызов не даст ничего информативного, так как у класса Vichecle не переопределён метод toString()

2024-02-28 08:46 UTC, Smirnoffspb78 commented on src/com/smirnov/project/lesson09/homework09/Vehicle.java
> +    private int number;
final быть не может, т.к. ТС может продаваться/ перерегистрироваться, но сделал setter

2024-02-28 10:10 UTC, Smirnoffspb78 commented on src/com/smirnov/project/lesson09/homework09/Workshop.java
> +     * @throws IllegalArgumentException - если дина Vehicle не положительная
"Отрицательная" не пойдет, т.к. нуль ни положительно ни отрицательное число, а создавать мастерскую с размером нуль такое

2024-03-03 10:44 UTC, merged