Выполнено ДЗ 11
Smirnoffspb78/lessons pull request #7
Opened 2024-03-06 06:43 UTC by Smirnoffspb78

2024-03-06 13:01 UTC, daniiladamov requested changes

2024-03-06 13:01 UTC, daniiladamov commented on src/com/smirnov/project/lesson12/homework12/animals/Animal.java
> +        if (o == null || getClass() != o.getClass()) return false;
см. Wolf

2024-03-10 15:27 UTC, daniiladamov commented on src/com/smirnov/project/lesson12/homework12/images/Gallery.java
> +
а чего удалил аннотацию Override? на методе draw() то стоит, а тут почему нет

2024-03-10 15:28 UTC, daniiladamov commented on src/com/smirnov/project/lesson12/homework12/images/Gallery.java
> +        Gallery gallery = new Gallery(getName(), drawablesCopy); //Это то, что мы должны вернуть. В галерею входят картинки и другие галереи
вместо getName можно напрямую обращаться к полю, ты же внутри класса

2024-03-10 19:51 UTC, Smirnoffspb78 commented on src/com/smirnov/project/lesson12/homework12/images/Gallery.java
> +
А это потому, что у меня как раз был вопрос по тому, как реализуется clone, но сейчас стало понятно

2024-03-10 19:57 UTC, merged