Выполнена курсовая работа
Smirnoffspb78/lessons pull request #8
Opened 2024-03-09 12:35 UTC by Smirnoffspb78

Выполнена курсовая работа.

2024-03-09 14:30 UTC, daniiladamov requested changes

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/SeasonTicket.java
> +     * @throws IllegalArgumentException Если ownerSeasonTicket=null. Если number отрицательный или 0
1. Так, исключения вы вроде прошли судя по урокам, поэтому: IllegalArgumentException - это непроверяемое исключение, если его описывать, то это делается не в теге @throws, а, например, в описании поля и его условий. Оставь этот тег для проверяемых исключений
2. Я бы в таком случае предложил использовать не конструктор, а статический метод, например, SeasonTicket.oneTime(owner), который вызывает следующий конструктор. Так как будет больше ясности в типе создаваемого объекта.
3. У тебя могу быть абонементы с одинаковым номером

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/SeasonTicket.java
> +     * @throws IllegalArgumentException Если typeSeasonTicket null или ONE_TIME. Если dateOfRegistration не позднее dateOfRegistration
см. выше

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/SeasonTicket.java
> +        if (typeSeasonTicket == null || typeSeasonTicket == ONE_TIME || !dateEnding.isAfter(dateOfRegistration)) {
ограничение на константу - костыль, почему клиент не может использовать этот конструктор с одной из констант

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/SeasonTicket.java
> +            throw new IllegalArgumentException("ownerSeasonTicket не может быть null");
в таком случае надо NullPointerException выбрасывать
и нужен ли вообще сеттер на это поле то?

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/SeasonTicket.java
> +        return "%s".formatted(ownerSeasonTicket);
очень странный метод, в таком случае, можно просто ownerSeasonTicket.toString() вывести

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/SeasonTicket.java
> +    private LocalDate dateEnding;
мб поле дб final?
вопрос к этому и двум следующим полям

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/OwnerSeasonTicket.java
> +    private String name;
мб поле дб final? к этому и следующему полю вопрос

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/OwnerSeasonTicket.java
> +public class OwnerSeasonTicket {
название)

2024-03-09 14:30 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1/Fitness.java
> +public enum Fitness {
вот это не лучшее решение
1. У тебя невозможно создать новый объект Фитнеса
2. Иерархию не построить
3. Почему фитнес является бассейном, спортивным залом и групповым занятием - не понятно. 
4. Между зонами и фитнесом явно есть ассоциация в виде композиции, а тут все очень странно.
5. Самое странное что я увидел - это ссылки на "фитнес" в типе абонемента. Поэтому я могу из типа абонемента получить все абонементы, что?
6. Это перечисление явно должно быть зонами фитнеса, а не фитнесом
7. Хранить и менять состояние в перечислении - такое себе решение, все-таки enum-ы нужны для работы с константами разной сложности, а не превращения их в подобие объекта с изменяющимся состоянием

2024-03-10 10:55 UTC, daniiladamov approved these changes

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Membership.java
> +        return "%s".formatted(ownerMembership);
зачем тут форматирование, эта инфа о владельце какая-то, а не об абонементе?
ownerMembership.toString(), если только эту инфу будешь оставлять

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Membership.java
> +        if (typeMembership == TypeMembership.ONE_TIME) {
блок норм смотрелся бы в тернарном операторе, тут всё ж просто

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Membership.java
> +            this.dateEnding = LocalDate.now().plusDays(1);
LocalDate.now() можно не вызывать, это значение у тебя в dateOfRegistration уже есть

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Membership.java
> +        number = id++;
первый абонемент будет нулевым, мож преинкремент забацать?

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +    private final OwnerMembership defaultOwner = new OwnerMembership("DefaultName", "DefaultSurname", LocalDate.now().getYear() - 1);
смысла нет в поле каждого объекта держать дефолтного пользователя и дефолтный абонемент, они отношения к фитнесу не имеют
Лучше создавай их в месте, где вызывается соответствующий метод, нигде, кроме этого метода они не будут же нужны

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +                counterGym = 0;
у тебя ж массив полностью заполненным становится, почему указатель тогда на 0, а не 19? Тут логика тогда проседает, если есть объект в массиве, то место занято, не важно какой это абонемент (ты жы конструктором выдаешь полностью функционируемый объект)

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +    public void addDefaultTicket(TypeFitness typeFitness) {
если я его вызову этот метод после наполнения клиентскими пользователями по одному, то изменения в массиве переданного типа затрутся

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +            if (memberships[i] == membership) {
почему сравниваешь ссылки в куче, а не состояние объекта? Вот тут уже можно было бы и equals() реализовать у абонемента

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +     * @return true/false если абонемент присутствует/не присутствует в секции
1. не ври мне!) если присутствует - ты false отдаёшь
2. Мог бы метод назвать по-другому, чтобы было понятно, что он проверяет отсутствие, а не просто что-то проверяет
3. Метод уже лишний, как по мне, ты в него передаешь уже те же поля, что и так у объекта уже есть (массив и счетчик). По факту тут только membership является данными извне
4. Параметр typeFitness вообще только для логов нужен - это уже плохой сигнал о переборе в делении метода на два

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        if (!checkMembership(membershipsGym, counterGym, membership, GYM)) {
1. В целом тут деление метода на два уже лишнее - см. выше
2. Если бы и делать так, то тут явно можно без блоков обоейтись if if-else и else, а реализовать все с использованием логических операторов && - это было бы читабельнее

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        for (int i = 0; i < membership.getTypeMembership().getTypeFitness().length; i++) {
1. membership.getTypeMembership().getTypeFitness() - вынести в локальную переменную
2. Красивее было бы, если тип TypeMembership мог принять TypeFitness в качестве аргумента и проверить его наличии в своём внутреннем массиве (типа метода contains()), так как между этими константами есть свзяь

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/TypeMembership.java
> +public enum TypeMembership {
Вообще, в английском порядок слов в прямом написании (без Of) противоположный (Тип абонемента - Type of Membership или Membership Type)

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +public class Fitness {
Общее
1. Пиши методы в порядке, облегчающем чтение класса (у тебя сейчас в перемешку вспомогательные и  публичные методы, нужно, чтобы код нормально читался сверху вниз другим программистом)
2. Комменты в приватных метода - у тебя там код не требует пояснения, а глобально - это детали внутренней реализации, так что их наличие только класс увеличивает и твоё затраченное время

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        if (!checkedZone || membership.getTypeMembership().getBeginTime().isAfter(LocalTime.now())
1. membership.getTypeMembership() - в локальную переменную
2. Эти проверки можно реализовать внутри TypeMembership, выставив наверх удобный метод

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        } else if (!LocalDate.now().isBefore(membership.getDateEnding())) {
в чем тут смысл else if? Тут проверки идут друг за другом, там что и if бы подошел, тем более у тебя тут нет завещающего else, т.е код просто проверяет каждый блок друг за другом и продолжается

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        if (!checkRegistration(membership)) {
у тебя метод вспомогательный вызывается один раз, а ты его уже через отрицание вызываешь (!), просто можно метод назвать не абстрактно "check..", а по-нормальному, тогда будет все читаться ясно и не надо отрицание вызывать

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        logger.info("%s добавлен в группу %s%nДата и время посещения: %s".formatted(membership.getOwnerMembership(), typeFitness.getName(), LocalDateTime.now()));
не добавлен ещё,  добавление идёт же после у тебя, и всё теоретически может упасть после этого лога

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        System.out.printf("%s: %s%n%s: %s%n%s: %s%n", GYM.getName(), Arrays.toString(getMembershipsGym()),
Я бы написал более удобочитаемо, это какой-то эльфийский уже)

2024-03-10 10:55 UTC, daniiladamov commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +    public Membership[] getMembershipsGym() {
Для методов ниже посмотри метод Arrays.copyOf() с двумя аргументами, он делает всё тоже самое, только в одну строчку

2024-03-10 16:01 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject1var2/Membership.java
> +        return "%s".formatted(ownerMembership);
Да я короче поправил и залил в третий коммит, но поправил вс тарой версии, а в новой версии не поправил, хотья думал, что правлю новую версию)

2024-03-10 16:20 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +    public void addDefaultTicket(TypeFitness typeFitness) {
Я так понял из контекста задания, что это и требуется. Мы берем целиком массив и заполняем его дефолтными значениями

"У Фитнеса должен быть реализован функционал по заполнению массивов абонементов дефолтными значениями".

2024-03-10 16:30 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +            if (memberships[i] == membership) {
Можно сделать и так и так. С ссылками проще. Номер у каждого объекта свой, уникальный, т.к. он инкрементируемый. Остальное все может быть идентично (один пользователь купил свое имя несколько абонементов одного типа в один день). Тогда и еквалс не нужно переопределять, а просто getNumber - это быстрее и проще, т.к. именно он гарантирует то, что каждый созданный новый объект уникальный. Так если мы знаем, что каждый созданный объект уникальный, то зачем городить огород?

2024-03-10 16:42 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +                counterGym = 0;
Я расценил заполнение дефолтными объектами массив, как функцию очистки массива. Т.к. дефолтный пользователь - это не пользователь, то значит мы поверх них можем записывать других пользователей.

2024-03-10 19:03 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +     * @return true/false если абонемент присутствует/не присутствует в секции
1) Да, все так
2) +
3, 4)"Метод уже лишний, как по мне, ты в него передаешь уже те же поля, что и так у объекта". Здесь дело в том, что мы туда передаем поочередно массивы. Цикл перебора мы  реализовали отдельно, чтобы не копипастить для четырех массивов. Во избежании дублирования кода, вынести цикл за метод оправдано. Суммарное использование метода - 3 раза.

2024-03-10 19:43 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        } else if (!LocalDate.now().isBefore(membership.getDateEnding())) {
Здесь else if логически связан на мой взгляд с проверкой абонемента по разным условиям, поэтому в else if выглядит неплохо. Этот elseif сокращает количество строк кода, что лучше должно восприниматься

2024-03-10 19:45 UTC, Smirnoffspb78 commented on src/com/smirnov/project/courseproject1var2/Fitness.java
> +        } else if (!LocalDate.now().isBefore(membership.getDateEnding())) {
Можно вообще все один if запихать, но как-будто 20 условий тяжело воспринимаются

2024-03-17 14:06 UTC, merged